name: edoctorug

version: 1.0.1+2  # version_name+build_number (required for Play Store)

environment:
  sdk: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^1.6.0
  provider: ^6.0.5
  web_socket_channel: ^2.4.0
  shared_preferences: ^2.5.5
  flutter_html: ^3.0.0-beta.2


flutter:
  uses-material-design: true

  assets:
    - assets/images/